/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package screen.craof.produzirInsumo;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import org.controle.craof.Controle_Insumos_Produzidos;
import org.entidade.craof.Insumo;
import org.entidade.craof.ProducaoInsumo;
import screen.craof.FrameAuxiliar;
import screen.craof.SegundaTela;
import screen.craof.fichas.CompraInsumos.CompraInsumosBuscar;
import screen.craof.insumo.PanelInsumoBuscar;

/**
 *
 * @author Luan
 */
public class ProduzirInsumo extends javax.swing.JPanel {

    /**
     * Creates new form CompraInsumos
     */
    public ProduzirInsumo(FrameAuxiliar frameAuxiliar) throws SQLException {
        initComponents();
        this.frameAuxiliar = frameAuxiliar;
        wtInsumo.setEnabled(false);
        wtInsumo.setText("Clique em buscar!!");
        producao = new ProducaoInsumo();
        controle = new Controle_Insumos_Produzidos();
        wtCodigo.setText(controle.maximoId());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFormattedTextField1 = new javax.swing.JFormattedTextField();
        jPasswordField1 = new javax.swing.JPasswordField();
        wtInsumo = new javax.swing.JTextField();
        wtCodigo = new javax.swing.JTextField();
        wlData = new javax.swing.JLabel();
        buscarInsumo = new javax.swing.JButton();
        wtData = new javax.swing.JTextField();
        try{
            javax.swing.text.MaskFormatter data = new javax.swing.text.MaskFormatter("##/##/####");
            wtData = new javax.swing.JFormattedTextField(data);
        }catch(Exception e){
        }
        wtQuantidade = new javax.swing.JTextField();
        salvar = new javax.swing.JButton();
        wlQuantidade = new javax.swing.JLabel();
        cancelar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        wlCodigo = new javax.swing.JLabel();
        wlInsumo = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();

        jFormattedTextField1.setText("jFormattedTextField1");

        jPasswordField1.setText("jPasswordField1");

        wtInsumo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        wtCodigo.setEditable(false);
        wtCodigo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        wtCodigo.setText("Automático");

        wlData.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        wlData.setText("Data:");

        buscarInsumo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        buscarInsumo.setText("BUSCAR");
        buscarInsumo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarInsumoActionPerformed(evt);
            }
        });

        wtData.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        wtData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wtDataActionPerformed(evt);
            }
        });

        wtQuantidade.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        salvar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        salvar.setText("SALVAR");
        salvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salvarActionPerformed(evt);
            }
        });

        wlQuantidade.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        wlQuantidade.setText("Quantidade");

        cancelar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cancelar.setText("CANCELAR");
        cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("PRODUÇÃO DE INSUMOS");

        wlCodigo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        wlCodigo.setText("Código:");

        wlInsumo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        wlInsumo.setText("Insumo:");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/craof80.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addGap(73, 73, 73)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(52, 161, Short.MAX_VALUE)
                .addComponent(salvar)
                .addGap(18, 18, 18)
                .addComponent(cancelar)
                .addGap(141, 141, 141))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 101, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(wlQuantidade)
                    .addComponent(wlInsumo, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(wlData, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(wlCodigo, javax.swing.GroupLayout.Alignment.LEADING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(wtCodigo)
                    .addComponent(wtData)
                    .addComponent(wtQuantidade)
                    .addComponent(wtInsumo, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(buscarInsumo)
                .addGap(77, 77, 77))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(wlCodigo)
                    .addComponent(wtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(wlData)
                    .addComponent(wtData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buscarInsumo)
                    .addComponent(wtInsumo, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(wlInsumo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(wtQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(wlQuantidade))
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(salvar)
                    .addComponent(cancelar))
                .addContainerGap(36, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void buscarInsumoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarInsumoActionPerformed
        FrameAuxiliar c = new FrameAuxiliar(this);
        c.abrirPanel(new PanelInsumoBuscar(c), "Buscar Insumo - CRAOF");
        c.setVisible(true);
    }//GEN-LAST:event_buscarInsumoActionPerformed

    private void salvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salvarActionPerformed
        if (!wtData.getText().equals("")) {
            if (!wtInsumo.getText().equals("")) {
                if (!wtQuantidade.getText().equals("")) {
                    controle = new Controle_Insumos_Produzidos();
                    producao.setData(wtData.getText());
                    producao.setQuantidade(Integer.parseInt(wtQuantidade.getText()));
                    try {
                        if (!controle.salvar(producao)) {
                            JOptionPane.showMessageDialog(null, "Compra de insumo salvo com sucesso!");
                            FrameAuxiliar frame = (FrameAuxiliar) frameAuxiliar;
                            ((ProduzirInsumoBuscar) frame.getPanel()).atualizarTabela(producao);
                            frame.fechar();
                        } else {
                            JOptionPane.showMessageDialog(null, "ERROR CRAOFx03 : Falha ao salvar compra de insumos!");
                        }
                    } catch (SQLException ex) {
                        Logger.getLogger(ProduzirInsumo.class.getName()).log(Level.SEVERE, null, ex);
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "ERROR CRAOFx04 : Preencher o campo Quantidade.");
                }
            } else {
                JOptionPane.showMessageDialog(null, "ERROR CRAOFx04 : Preencher o campo Insumo.");
            }
        } else {
            JOptionPane.showMessageDialog(null, "ERROR CRAOFx04 : Preencher o campo Data.");
        }
    }//GEN-LAST:event_salvarActionPerformed

    private void cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarActionPerformed
        frameAuxiliar.fechar();
    }//GEN-LAST:event_cancelarActionPerformed

    private void wtDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wtDataActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_wtDataActionPerformed

    public JTextField getWtInsumo() {
        return wtInsumo;
    }

    public void setInsumo(Insumo insumo) {
        this.wtInsumo.setText(insumo.getDescricao());
        producao.setInsumo(insumo);
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buscarInsumo;
    private javax.swing.JButton cancelar;
    private javax.swing.JFormattedTextField jFormattedTextField1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton salvar;
    private javax.swing.JLabel wlCodigo;
    private javax.swing.JLabel wlData;
    private javax.swing.JLabel wlInsumo;
    private javax.swing.JLabel wlQuantidade;
    private javax.swing.JTextField wtCodigo;
    private javax.swing.JTextField wtData;
    private javax.swing.JTextField wtInsumo;
    private javax.swing.JTextField wtQuantidade;
    // End of variables declaration//GEN-END:variables
    private FrameAuxiliar frameAuxiliar;
    private ProducaoInsumo producao;
    private Controle_Insumos_Produzidos controle;

}
