/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package screen.craof;

import java.awt.CardLayout;
import java.awt.Container;
import java.awt.Rectangle;
import java.awt.event.ActionEvent;
import javax.swing.BoxLayout;
import javax.swing.JFrame;
import javax.swing.JPanel;

/**
 *
 * @author Luan
 */
public class SegundaTela extends javax.swing.JFrame {

    /**
     * Creates new form SegundaTela
     */
    public SegundaTela(Principal principal){
        this.principal = principal;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tela = new javax.swing.JPanel();

        setTitle("CRAOF");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        javax.swing.GroupLayout telaLayout = new javax.swing.GroupLayout(tela);
        tela.setLayout(telaLayout);
        telaLayout.setHorizontalGroup(
            telaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 214, Short.MAX_VALUE)
        );
        telaLayout.setVerticalGroup(
            telaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 248, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(tela, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(46, Short.MAX_VALUE)
                .addComponent(tela, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
       voltar();
    }//GEN-LAST:event_formWindowClosed

    public void setMenu(JPanel menu) {
        this.menu = menu;
        setTela(menu);

    }

    public void setTela(JPanel tela) {
        contentPane = getContentPane();
        cardLayout = new CardLayout();
        contentPane.setLayout(new BoxLayout(contentPane, BoxLayout.Y_AXIS));
        this.tela.setLayout(cardLayout);
        this.tela.removeAll();
        this.tela.setVisible(false);
        this.tela.setVisible(true);
        this.tela.setEnabled(true);
        this.tela.add(tela, "Cadastro de Local");
        contentPane.add(this.tela);
        cardLayout.show(this.tela, "Painel 1");
        corrigir();
    }

    public void corrigir() {

        tela.setBounds(new Rectangle(10, 10, tela.getPreferredSize().width,
                tela.getPreferredSize().height));
        tela.repaint();
        this.setBounds(new Rectangle(0, 0, tela.getPreferredSize().width+50,
                tela.getPreferredSize().height+50));
        repaint();

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel tela;
    // End of variables declaration//GEN-END:variables
    Principal principal;
    JPanel menu;
    Container contentPane;
    CardLayout cardLayout;

    public void voltar() {
        principal.setVisible(true);
        //dispose();
  
        this.setVisible(false);
    }

    public void fecharPanel() {
        setTela(menu);
    }
    
    

}
